# Generated by Django 4.2.16 on 2025-11-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncaoSintatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OracaoPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OracaoSubordinada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=80)),
                ('oracao', models.TextField()),
                ('fk_funcao_sintatica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguistica.funcaosintatica')),
                ('fk_oracao_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguistica.oracaoprincipal')),
            ],
        ),
    ]
